FROM python:3.12

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8051

CMD ["streamlit", "run", "scripts/streamlit_app.py", "--server.port=8051", "--server.address=0.0.0.0"]