FROM python:3.12

WORKDIR /app

COPY requirements-streamlit.txt .

RUN pip install --no-cache-dir -r requirements-streamlit.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "scripts/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
